export const AUTH = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
    LOGIN_REQUEST_ERROR: 'LOGIN_REQUEST_ERROR',
}

export const SIGNUP = {
    SIGN_REQUEST: 'SIGN_REQUEST',
    SIGN_REQUEST_SUCCESS: 'SIGN_REQUEST_SUCCESS',
    SIGN_REQUEST_ERROR: 'SIGN_REQUEST_ERROR',
}

export const LOGOUT = {
    LOGOUT_REQUEST: 'LOGOUT',
    LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
    LOGOUT_REQUEST_ERROR: 'LOGOUT_REQUEST_ERROR',
}